import { Mali } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const mali = Mali({
  variable: "--font-mali",
  subsets: ["thai"],
  weight: ["200","300","400","500","600","700"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${mali.variable}  antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
